name: "twitch_chat_pipeline_v2"
version: "1.0.0"
profile: "twitch_chat_pipeline_v2"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"

models:
  twitch_chat_pipeline_v2:
    staging:
      +materialized: view
    intermediate:
      +materialized: ephemeral
    marts:
      +materialized: table
flags:
  require_generic_test_arguments_property: true
