version: 2

sources:
  - name: silver
    database: workspace
    schema: twitch_pipeline_silver
    tables:
      - name: twitch_chat_parsed
        identifier: twitch_chat_parsed
        description: "Silver table with parsed chat messages and features"
        
        data_tests:
          - dbt_utils.unique_combination_of_columns:
              combination_of_columns:
                - topic
                - partition
                - offset 
        
        columns:
          - name: topic
            description: "Kafka topic name"
            tests:
              - not_null
          - name: partition
            description: "Kafka partition number"
            tests:
              - not_null
          - name: offset
            description: "Kafka offset"
            tests:
              - not_null
          - name: user
            description: "Twitch username of the chat message sender"
            tests:
              - not_null
          - name: message
            description: "Content of the chat message"
            tests:
              - not_null
          - name: sent_compound
            description: "Sentiment compound score between -1.0 and 1.0"
            tests:
              - dbt_utils.expression_is_true:
                  expression: "BETWEEN -1.0 AND 1.0"
          - name: sent_pos
            description: "Sentiment positive score between 0.0 and 1.0"
            tests:
              - dbt_utils.expression_is_true:
                  expression: "BETWEEN 0.0 AND 1.0"
          - name: sent_neg
            description: "Sentiment negative score between 0.0 and 1.0"
            tests:
              - dbt_utils.expression_is_true:
                  expression: "BETWEEN 0.0 AND 1.0"
          - name: sent_neu
            description: "Sentiment neutral score between 0.0 and 1.0"
            tests:
              - dbt_utils.expression_is_true:
                  expression: "BETWEEN 0.0 AND 1.0"
          - name: message_length
            description: "Length of the chat message in characters"
            tests:
              - dbt_utils.expression_is_true:
                  expression: "> 0"
          - name: entropy
            description: "Shannon entropy of the chat message"
          - name: is_emote_only
            description: "Boolean flag indicating if the message contains only emotes"
          - name: emote_count
            description: "Number of emotes in the chat message"
          - name: repeat_char_ratio
            description: "Ratio of repeated characters in the chat message"
          - name: alpha_ratio
            description: "Ratio of alphabetic characters in the chat message"
          - name: engagement_flag
            description: "Boolean flag indicating if the message contains engagement"
            tests:
              - not_null
          - name: kafka_timestamp
            description: "Original Kafka message timestamp"
          - name: ingest_ts
            description: "Timestamp when the message was ingested into the silver table"
            tests:
              - not_null